export default `<?xml version="1.0" encoding="UTF-8"?>
<pnml>
<net type="http://www.pnml.org/version-2009/grammar/pnmlcoremodel" id="Generated by Petri Net Editor">
    <name>
        <text>Generated by Petri Net Editor</text>
    </name>
    <page id="page-1">
       <place id="place-5">
            <name>
                <text>place-5</text>
            </name>
            <graphics>
                <position x="10" y="-54"/>
            </graphics>
            <toolspecific tool="ProM" version="6.4" localNodeID="84802b06-eb14-490a-892d-0e22ef1ae24f" />
       </place>
       <place id="place-8">
            <name>
                <text>place-8</text>
            </name>
            <graphics>
                <position x="246" y="144"/>
            </graphics>
            <toolspecific tool="ProM" version="6.4" localNodeID="b88a249a-3621-48af-8f91-249632d65931" />
       </place>
       <place id="place-9">
            <name>
                <text>place-9</text>
            </name>
            <graphics>
                <position x="246" y="-54"/>
            </graphics>
            <toolspecific tool="ProM" version="6.4" localNodeID="3716cfcc-598d-4596-a64d-c523162fef2b" />
       </place>
       <place id="place-12">
            <name>
                <text>place-12</text>
            </name>
            <graphics>
                <position x="480" y="-54"/>
            </graphics>
            <toolspecific tool="ProM" version="6.4" localNodeID="d4cfea4a-5876-402c-a480-5df94e447e99" />
       </place>
       <place id="place-14">
            <name>
                <text>place-14</text>
            </name>
            <graphics>
                <position x="480" y="144"/>
            </graphics>
            <toolspecific tool="ProM" version="6.4" localNodeID="7b398a5c-6400-4181-90a6-9171f8eed694" />
       </place>
       <place id="place-17">
            <name>
                <text>place-17</text>
            </name>
            <graphics>
                <position x="681" y="44"/>
            </graphics>
            <toolspecific tool="ProM" version="6.4" localNodeID="02cfa26c-2466-4998-a73b-cc52e6793eac" />
       </place>
       <transition id="transition-7" invisible="true">
            <name>
                <text>action</text>
            </name>
            <graphics>
                <position x="103" y="-59"/>
            </graphics>
            <toolspecific tool="ProM" version="6.4" localNodeID="3e62a03d-0567-4696-9741-f9dd6fc9d5fc" activity="$invisible$"/>
       </transition>
       <transition id="transition-10" invisible="false">
            <name>
                <text>a</text>
            </name>
            <graphics>
                <position x="359" y="-59"/>
            </graphics>
            <toolspecific tool="ProM" version="6.4" localNodeID="b5ddcb02-caf5-4589-a91b-05889adeecb9" activity=""/>
       </transition>
       <transition id="transition-11" invisible="false">
            <name>
                <text>b</text>
            </name>
            <graphics>
                <position x="359" y="39"/>
            </graphics>
            <toolspecific tool="ProM" version="6.4" localNodeID="67028e7d-43a7-47e6-a384-0e6947afa8d2" activity=""/>
       </transition>
       <transition id="transition-13" invisible="false">
            <name>
                <text>c</text>
            </name>
            <graphics>
                <position x="359" y="139"/>
            </graphics>
            <toolspecific tool="ProM" version="6.4" localNodeID="42bb413e-9ac5-41ae-a333-f9fc48a6af5b" activity=""/>
       </transition>
       <transition id="transition-15" invisible="true">
            <name>
                <text>action</text>
            </name>
            <graphics>
                <position x="359" y="233"/>
            </graphics>
            <toolspecific tool="ProM" version="6.4" localNodeID="c19a6db8-c2d6-4bbf-9c23-762f4bb6e895" activity="$invisible$"/>
       </transition>
       <transition id="transition-16" invisible="true">
            <name>
                <text>action</text>
            </name>
            <graphics>
                <position x="569" y="39"/>
            </graphics>
            <toolspecific tool="ProM" version="6.4" localNodeID="ca3c4d3b-c751-48ac-be29-30308e591f50" activity="$invisible$"/>
       </transition>
       <arc id="flow-12" source="place-5" target="transition-7">
            <toolspecific tool="ProM" version="6.4" localNodeID="e8d6d9f2-380b-44d1-a7ab-ab7a1598fe19" />
            <arctype>
                <text>normal</text>
            </arctype>
            <graphics>            
                <position x="35" y="-30"/>
                <position x="133" y="-30"/>
           </graphics>       
        </arc>
       <arc id="flow-14" source="transition-7" target="place-8">
            <toolspecific tool="ProM" version="6.4" localNodeID="57ccb4be-c9e4-4f9f-a05a-595069ca8c53" />
            <arctype>
                <text>normal</text>
            </arctype>
            <graphics>            
                <position x="133" y="-30"/>
                <position x="133" y="169"/>
                <position x="271" y="169"/>
           </graphics>       
        </arc>
       <arc id="flow-16" source="transition-7" target="place-9">
            <toolspecific tool="ProM" version="6.4" localNodeID="3d1d0e5b-ce13-458b-9a6b-bb914386d329" />
            <arctype>
                <text>normal</text>
            </arctype>
            <graphics>            
                <position x="133" y="-30"/>
                <position x="271" y="-30"/>
           </graphics>       
        </arc>
       <arc id="flow-17" source="place-9" target="transition-10">
            <toolspecific tool="ProM" version="6.4" localNodeID="52a25f83-d561-4a36-a1d6-80c6e53f7384" />
            <arctype>
                <text>normal</text>
            </arctype>
            <graphics>            
                <position x="271" y="-31"/>
                <position x="389" y="-30"/>
           </graphics>       
        </arc>
       <arc id="flow-18" source="place-9" target="transition-11">
            <toolspecific tool="ProM" version="6.4" localNodeID="10adbdfc-1093-4b41-a3c5-c7e9c6649e7a" />
            <arctype>
                <text>normal</text>
            </arctype>
            <graphics>            
                <position x="271" y="-30"/>
                <position x="271" y="69"/>
                <position x="389" y="69"/>
           </graphics>       
        </arc>
       <arc id="flow-19" source="transition-11" target="place-12">
            <toolspecific tool="ProM" version="6.4" localNodeID="201f8661-873f-4170-af0a-a168c2dc806e" />
            <arctype>
                <text>normal</text>
            </arctype>
            <graphics>            
                <position x="389" y="69"/>
                <position x="505" y="69"/>
                <position x="505" y="-30"/>
           </graphics>       
        </arc>
       <arc id="flow-21" source="transition-10" target="place-12">
            <toolspecific tool="ProM" version="6.4" localNodeID="93fd3088-b10c-497e-a049-bbd656ba64e0" />
            <arctype>
                <text>normal</text>
            </arctype>
            <graphics>            
                <position x="389" y="-30"/>
                <position x="505" y="-30"/>
           </graphics>       
        </arc>
       <arc id="flow-22" source="place-8" target="transition-13">
            <toolspecific tool="ProM" version="6.4" localNodeID="43875f2b-1fd3-48cd-8c2d-be396c756ef3" />
            <arctype>
                <text>normal</text>
            </arctype>
            <graphics>            
                <position x="271" y="169"/>
                <position x="389" y="169"/>
           </graphics>       
        </arc>
       <arc id="flow-23" source="transition-13" target="place-14">
            <toolspecific tool="ProM" version="6.4" localNodeID="bfe671ca-71ae-47ab-8488-c7eb37de897c" />
            <arctype>
                <text>normal</text>
            </arctype>
            <graphics>            
                <position x="389" y="169"/>
                <position x="505" y="169"/>
           </graphics>       
        </arc>
       <arc id="flow-24" source="place-14" target="transition-15">
            <toolspecific tool="ProM" version="6.4" localNodeID="07bb6cd8-0bb9-41bb-8de7-a5d2dadf7dac" />
            <arctype>
                <text>normal</text>
            </arctype>
            <graphics>            
                <position x="505" y="169"/>
                <position x="505" y="268"/>
                <position x="394" y="268"/>
           </graphics>       
        </arc>
       <arc id="flow-26" source="transition-15" target="place-8">
            <toolspecific tool="ProM" version="6.4" localNodeID="519ace7f-30a1-4bee-a46b-ded16c3704ac" />
            <arctype>
                <text>normal</text>
            </arctype>
            <graphics>            
                <position x="389" y="263"/>
                <position x="271" y="263"/>
                <position x="271" y="169"/>
           </graphics>       
        </arc>
       <arc id="flow-27" source="place-14" target="transition-16">
            <toolspecific tool="ProM" version="6.4" localNodeID="d3cb8e16-259a-4eb2-a6f6-25f5402b1080" />
            <arctype>
                <text>normal</text>
            </arctype>
            <graphics>            
                <position x="505" y="169"/>
                <position x="604" y="169"/>
                <position x="604" y="74"/>
           </graphics>       
        </arc>
       <arc id="flow-29" source="place-12" target="transition-16">
            <toolspecific tool="ProM" version="6.4" localNodeID="531e0d37-9836-4310-9349-dc98b20781fd" />
            <arctype>
                <text>normal</text>
            </arctype>
            <graphics>            
                <position x="505" y="-31"/>
                <position x="599" y="-31"/>
                <position x="599" y="69"/>
           </graphics>       
        </arc>
       <arc id="flow-30" source="transition-16" target="place-17">
            <toolspecific tool="ProM" version="6.4" localNodeID="76836f30-c123-4b5e-9200-b4b84e281867" />
            <arctype>
                <text>normal</text>
            </arctype>
            <graphics>            
                <position x="599" y="69"/>
                <position x="706" y="69"/>
           </graphics>       
        </arc>
   </page>
</net>
</pnml>

`