export default `<?xml version="1.0" encoding="UTF-8"?>
<pnml>
<net type="http://www.pnml.org/version-2009/grammar/pnmlcoremodel" id="Generated by Petri Net Editor">
    <name>
        <text>Generated by Petri Net Editor</text>
    </name>
    <page id="page-1">
       <place id="place-5">
            <name>
                <text>place-5</text>
            </name>
            <graphics>
                <position x="-12" y="-76"/>
            </graphics>
            <toolspecific tool="ProM" version="6.4" localNodeID="ac1acead-3e7e-418d-bd04-033c9bdad594" />
       </place>
       <place id="place-8">
            <name>
                <text>place-8</text>
            </name>
            <graphics>
                <position x="221" y="119"/>
            </graphics>
            <toolspecific tool="ProM" version="6.4" localNodeID="9477b480-da66-463f-9743-d6af15d102f4" />
       </place>
       <place id="place-9">
            <name>
                <text>place-9</text>
            </name>
            <graphics>
                <position x="221" y="-76"/>
            </graphics>
            <toolspecific tool="ProM" version="6.4" localNodeID="6550d9cb-c798-4629-9a00-a42d6ee8a1ed" />
       </place>
       <place id="place-12">
            <name>
                <text>place-12</text>
            </name>
            <graphics>
                <position x="455" y="-76"/>
            </graphics>
            <toolspecific tool="ProM" version="6.4" localNodeID="8bd60168-18df-4223-bb00-4dfa290d9621" />
       </place>
       <place id="place-14">
            <name>
                <text>place-14</text>
            </name>
            <graphics>
                <position x="455" y="119"/>
            </graphics>
            <toolspecific tool="ProM" version="6.4" localNodeID="fdba7780-d268-40a2-a225-c75243cf1e94" />
       </place>
       <place id="place-17">
            <name>
                <text>place-17</text>
            </name>
            <graphics>
                <position x="656" y="14"/>
            </graphics>
            <toolspecific tool="ProM" version="6.4" localNodeID="911691ec-2bf1-4749-9477-756f641eff49" />
       </place>
       <transition id="transition-7" invisible="true">
            <name>
                <text>action</text>
            </name>
            <graphics>
                <position x="103" y="-82"/>
            </graphics>
            <toolspecific tool="ProM" version="6.4" localNodeID="550b3b56-b23e-4563-906c-9c5c6b23d343" activity="$invisible$"/>
       </transition>
       <transition id="transition-10" invisible="false">
            <name>
                <text>a</text>
            </name>
            <graphics>
                <position x="329" y="-81"/>
            </graphics>
            <toolspecific tool="ProM" version="6.4" localNodeID="a77aeaec-04ea-4b4a-a293-a44bf780e353" activity=""/>
       </transition>
       <transition id="transition-11" invisible="false">
            <name>
                <text>b</text>
            </name>
            <graphics>
                <position x="329" y="9"/>
            </graphics>
            <toolspecific tool="ProM" version="6.4" localNodeID="b6f9a240-17c8-4cf5-99cb-ce990501962f" activity=""/>
       </transition>
       <transition id="transition-13" invisible="false">
            <name>
                <text>c</text>
            </name>
            <graphics>
                <position x="329" y="114"/>
            </graphics>
            <toolspecific tool="ProM" version="6.4" localNodeID="a38eaf78-e081-4d4d-bc78-d3a7d1abe996" activity=""/>
       </transition>
       <transition id="transition-15" invisible="true">
            <name>
                <text>action</text>
            </name>
            <graphics>
                <position x="344" y="203"/>
            </graphics>
            <toolspecific tool="ProM" version="6.4" localNodeID="e480d2ff-24ad-43ad-9e40-dd78c11338d7" activity="$invisible$"/>
       </transition>
       <transition id="transition-16" invisible="true">
            <name>
                <text>action</text>
            </name>
            <graphics>
                <position x="554" y="9"/>
            </graphics>
            <toolspecific tool="ProM" version="6.4" localNodeID="130b0d55-5001-4bfd-aaef-1f30626bd9a4" activity="$invisible$"/>
       </transition>
       <arc id="flow-12" source="place-5" target="transition-7">
            <toolspecific tool="ProM" version="6.4" localNodeID="f9b41349-4244-4a51-8297-7049b7ac6be1" />
            <arctype>
                <text>normal</text>
            </arctype>
            <graphics>            
                <position x="37" y="-52"/>
                <position x="103" y="-52"/>
           </graphics>       
        </arc>
       <arc id="flow-14" source="transition-7" target="place-8">
            <toolspecific tool="ProM" version="6.4" localNodeID="216d15fc-d063-4c6b-863d-695be127cc68" />
            <arctype>
                <text>normal</text>
            </arctype>
            <graphics>            
                <position x="118" y="-22"/>
                <position x="118" y="143"/>
                <position x="221" y="143"/>
           </graphics>       
        </arc>
       <arc id="flow-16" source="transition-7" target="place-9">
            <toolspecific tool="ProM" version="6.4" localNodeID="23d17c48-942d-46be-af1e-9f5cfe191cfe" />
            <arctype>
                <text>normal</text>
            </arctype>
            <graphics>            
                <position x="133" y="-52"/>
                <position x="221" y="-52"/>
           </graphics>       
        </arc>
       <arc id="flow-17" source="place-9" target="transition-10">
            <toolspecific tool="ProM" version="6.4" localNodeID="c2a5e6b7-151b-4ed3-af99-f7e855258e57" />
            <arctype>
                <text>normal</text>
            </arctype>
            <graphics>            
                <position x="271" y="-51"/>
                <position x="329" y="-51"/>
           </graphics>       
        </arc>
       <arc id="flow-18" source="place-9" target="transition-11">
            <toolspecific tool="ProM" version="6.4" localNodeID="446fa84a-2a5c-43cc-8d4a-ce6d118152d6" />
            <arctype>
                <text>normal</text>
            </arctype>
            <graphics>            
                <position x="246" y="-26"/>
                <position x="246" y="40"/>
                <position x="329" y="39"/>
           </graphics>       
        </arc>
       <arc id="flow-19" source="transition-11" target="place-12">
            <toolspecific tool="ProM" version="6.4" localNodeID="bc9d9e91-7d60-4616-8091-6e7e78088b9f" />
            <arctype>
                <text>normal</text>
            </arctype>
            <graphics>            
                <position x="389" y="39"/>
                <position x="479" y="39"/>
                <position x="479" y="-26"/>
           </graphics>       
        </arc>
       <arc id="flow-21" source="transition-10" target="place-12">
            <toolspecific tool="ProM" version="6.4" localNodeID="640f2371-2acd-429a-8f0e-9505aeb3b4e9" />
            <arctype>
                <text>normal</text>
            </arctype>
            <graphics>            
                <position x="389" y="-51"/>
                <position x="455" y="-51"/>
           </graphics>       
        </arc>
       <arc id="flow-22" source="place-8" target="transition-13">
            <toolspecific tool="ProM" version="6.4" localNodeID="128ee4d1-6268-4585-bb0f-0dcd809e4a19" />
            <arctype>
                <text>normal</text>
            </arctype>
            <graphics>            
                <position x="271" y="144"/>
                <position x="329" y="144"/>
           </graphics>       
        </arc>
       <arc id="flow-23" source="transition-13" target="place-14">
            <toolspecific tool="ProM" version="6.4" localNodeID="451a92b3-eb2d-46c7-9d8e-38c252f70091" />
            <arctype>
                <text>normal</text>
            </arctype>
            <graphics>            
                <position x="389" y="144"/>
                <position x="455" y="144"/>
           </graphics>       
        </arc>
       <arc id="flow-24" source="place-14" target="transition-15">
            <toolspecific tool="ProM" version="6.4" localNodeID="a99b0f25-d960-4cc1-aff5-7b5a716c1833" />
            <arctype>
                <text>normal</text>
            </arctype>
            <graphics>            
                <position x="480" y="169"/>
                <position x="480" y="233"/>
                <position x="374" y="233"/>
           </graphics>       
        </arc>
       <arc id="flow-26" source="transition-15" target="place-8">
            <toolspecific tool="ProM" version="6.4" localNodeID="9a5d46ad-d465-4bff-9026-5d34e5dcb214" />
            <arctype>
                <text>normal</text>
            </arctype>
            <graphics>            
                <position x="344" y="233"/>
                <position x="247" y="233"/>
                <position x="246" y="169"/>
           </graphics>       
        </arc>
       <arc id="flow-27" source="place-14" target="transition-16">
            <toolspecific tool="ProM" version="6.4" localNodeID="65588183-dbb2-45f6-b6c5-a31513b9b500" />
            <arctype>
                <text>normal</text>
            </arctype>
            <graphics>            
                <position x="505" y="144"/>
                <position x="570" y="144"/>
                <position x="569" y="69"/>
           </graphics>       
        </arc>
       <arc id="flow-29" source="place-12" target="transition-16">
            <toolspecific tool="ProM" version="6.4" localNodeID="f4627edf-20f0-41e7-8e07-20ea66ca425d" />
            <arctype>
                <text>normal</text>
            </arctype>
            <graphics>            
                <position x="505" y="-52"/>
                <position x="569" y="-53"/>
                <position x="569" y="9"/>
           </graphics>       
        </arc>
       <arc id="flow-30" source="transition-16" target="place-17">
            <toolspecific tool="ProM" version="6.4" localNodeID="bbb24df9-bc8d-468f-a4dd-2bff18d50e5d" />
            <arctype>
                <text>normal</text>
            </arctype>
            <graphics>            
                <position x="584" y="39"/>
                <position x="656" y="39"/>
           </graphics>       
        </arc>
   </page>
</net>
</pnml>


`